use_frameworks!

platform :ios, '9.0'

target 'UIKitBaseDemo' do
 pod 'UIKitBase', path: '../../'
 pod 'DinoDNA', :git => 'git@bitbucket.org:appsaurus/dinodna.git'
 pod 'UIKitTheme', :git => 'https://github.com/Appsaurus/UIKitTheme'
 pod 'UIKitMixinable', :git => 'https://github.com/Appsaurus/UIKitMixinable'
 pod 'UIKitExtensions', :git => 'https://github.com/Appsaurus/UIKitExtensions'
 pod 'UILayoutKit', :git => 'https://github.com/Appsaurus/UILayoutKit'
 pod 'DarkMagic', :git => 'https://github.com/Appsaurus/DarkMagic'
 pod 'UIFontIcons/MaterialIcons', :git => 'https://github.com/Appsaurus/UIFontIcons'
 pod 'Actions'
 pod 'Nuke'
end

